
export const skills = [
  [
    {
      label: "Alertness",
      type: "Talents",
      val: [
        "• Novice: “I’ve got a bad feeling about this…”",
        "•• Practiced: Your hackles rise at the first sign of trouble.",
        "••• Skillful: You catch the threat beneath a whispered voice.",
        "•••• Expert: You’ve already noted three attackersand mapped four avenues of escape.",
        "••••• Master: Those ninjas might as well be wearing pink neon clown suits.",
      ],
    },
    {
      label: "Art",
      type: "Talents",
      val: [
        "• Novice: You’re creative but unskilled.",
        "•• Practiced: You’ve put some time and work into your chosen medium.",
        "••• Skillful: Professional art could be a viable career option.",
        "•••• Expert: You’re a working pro whose work displays fascinating appeal and skill.",
        "••••• Master: You’re an acknowledged master of your field.",
      ],
    },
    {
      label: "Athletics",
      type: "Talents",
      val: [
        "• Novice: You were pretty decent in PE class.",
        "•• Practiced: Regular exercise is essential to your life.",
        "••• Skillful: You are one fit sonofabitch!",
        "•••• Expert: Gym-rats and pro athletes take notes from you.",
        "••••• Master: You could qualify for the Olympics… and you might actually compete!",
      ],
    },
    {
      label: "Awareness",
      type: "Talents",
      val: [
        "• Novice: You possess a gift for spotting hiddentruths.",
        "•• Practiced: Magic exists, and you often senseits presence.",
        "••• Skillful: You can see auras, and you understand what those colors mean.",
        "•••• Expert: The supernatural world reveals itself to you in disturbing detail.",
        "••••• Master: You’re so attuned to the mystic realm that many folks consider you insane.",
      ],
    },
    {
      label: "Brawl",
      type: "Talents",
      val: [
        "• Novice: You had a tough childhood.",
        "•• Practiced: You’re from The Bad Part of Town.",
        "••• Skillful: When punches fly, you’re among the last folks standing.",
        "•••• Expert: Extreme fighting champs shiver when you enter the ring.",
        "••••• Master: “See me hit you, you go down.”",
      ],
    },
    {
      label: "Empathy",
      type: "Talents",
      val: [
        "• Novice: You’re pretty decent at noticing emotional cues.",
        "•• Practiced: You’re the crying shoulder for your friends.",
        "••• Skillful: It’s fairly hard to deceive you.",
        "•••• Expert: Even below the surface, a person’s true feelings seem obvious to you.",
        "••••• Master: To your eyes, most people are open books.",
      ],
    },
    {
      label: "Expression",
      type: "Talents",
      val: [
        "• Novice: When you speak, folks notice.",
        "•• Practiced: Your passions capture other people’s interest.",
        "••• Skillful: You rock the crowd with a voice that’s loud.",
        "•••• Expert: In this media-glutted world, you still blaze bright.",
        "••••• Master: Poets, prophets, and politicians wish they were you. Possessed By: Rock Stars,",
      ],
    },
    {
      label: "Intimidation",
      type: "Talents",
      val: [
        "• Novice: Playground terror.",
        "•• Practiced: Clique leader.",
        "••• Skillful: Professional dominant.",
        "•••• Expert: Alpha wolf.",
        "••••• Master: Queen or king of all you survey.",
      ],
    },
    {
      label: "Leadership",
      type: "Talents",
      val: [
        "• Novice: Head cheerleader.",
        "•• Practiced: Quarterback.",
        "••• Skillful: Executive.",
        "•••• Expert: Tycoon.",
        "••••• Master: Nick Fury.",
      ],
    },
    {
      label: "Streetwise",
      type: "Talents",
      val: [
        "• Novice: Rock musician.",
        "•• Practiced: Suburban dope dealer.",
        "••• Skillful: Hip-Hop MC.",
        "•••• Expert: Gang leader.",
        "••••• Master: Gang lord. Possessed By: Bartenders, Hookers,",
      ],
    },
    {
      label: "Subterfuge",
      type: "Talents",
      val: [
        "• Novice: Cute kid.",
        "•• Practiced: Small-time hustler.",
        "••• Skillful: Successful lawyer.",
        "•••• Expert: Career politician.",
        "••••• Master: Master spy.",
      ],
    }
  ],
  [
    {
      label: "Crafts",
      type: "Skills",
      val: [
        "• Novice: You sorta know what you’re doing.",
        "•• Practiced: Basic skills have given way to working knowledge.",
        "••• Skillful: You’re pretty damn good, if you must say so yourself!",
        "•••• Expert: You’re highly respected within your field.",
        "••••• Master: There’s little you can’t do when you set your mind to doing it.",
      ],
    },
    {
      label: "Drive",
      type: "Skills",
      val: [
        "• Novice: Sunday driver.",
        "•• Practiced: Typical American.",
        "••• Skillful: New York taxi driver.",
        "•••• Expert: Professional racer.",
        "••••• Master: Bond – James Bond.",
      ],
    },
    {
      label: "Etiquette",
      type: "Skills",
      val: [
        "• Novice: You can attend fine restaurants without embarrassing yourself.",
        "•• Practiced: You’ve got impressive manners and a sense for saying the right things.",
        "••• Skillful: Wonderfully cultured, you know your way around a meal, party, or conversation.",
        "•••• Expert: A social chameleon, you put folks at ease almost anywhere.",
        "••••• Master: You’re a valued guest in nearly any situation.",
      ],
    },
    {
      label: "Firearms",
      type: "Skills",
      val: [
        "• Novice: Gun range newbie.",
        "•• Practiced: Hunter.",
        "••• Skillful: Typical cop or soldier.",
        "•••• Expert: Sharpshooter.",
        "••••• Master: Frank Castle.",
      ],
    },
    {
      label: "Martial Arts",
      type: "Skills",
      val: [
        "• Novice: Raw beginner.",
        "•• Practiced: Experienced student.",
        "••• Skillful: Devotee.",
        "•••• Expert: Accomplished combatant.",
        "••••• Master: Formidable master.",
      ],
    },
    {
      label: "Meditation",
      type: "Skills",
      val: [
        "• Novice: You can ground and center for short periods of time.",
        "•• Practiced: Regular practice has deepened and extended your abilities.",
        "••• Skillful: Even under distracting conditions, you know how to find your center.",
        "•••• Expert: “Use the Force, Luke…”",
        "••••• Master: An island of calm is yours whenever you want or need it.",
      ],
    },
    {
      label: "Melee",
      type: "Skills",
      val: [
        "• Novice: You can swing a club or blade around without hurting yourself… much.",
        "•• Practiced: You’ve earned a bit of skill… maybe even enough for a real-life fight.",
        "••• Skillful: You’re kinda badass.",
        "•••• Expert: You’re seriously badass.",
        "••••• Master: Your skill intimidates the pros.",
      ],
    },
    {
      label: "Research",
      type: "Skills",
      val: [
        "• Novice: Buffy.",
        "•• Practiced: Anya.",
        "••• Skillful: Willow.",
        "•••• Expert: Giles.",
        "••••• Master: Fred.",
      ],
    },
    {
      label: "Stealth",
      type: "Skills",
      val: [
        "• Novice: With dark clothes, you might not be spotted at night.",
        "•• Practiced: You often sneak out past your parents.",
        "••• Skillful: A genuine sneak, you elude casual detection.",
        "•••• Expert: Just doin’ what a ninja’s gotta do…",
        "••••• Master: Batman’s taking notes.",
      ],
    },
    {
      label: "Survival",
      type: "Skills",
      val: [
        "• Novice: You’ve done some day-hikes on established trails.",
        "•• Practiced: Plenty of time outdoors has taught you decent skills.",
        "••• Skillful: You can live off the land, make traps, and spot most obvious hazards.",
        "•••• Expert: You’d probably survive the Hunger Games.",
        "••••• Master: The wilderness is your full-time home.",
      ],
    },
    {
      label: "Technology",
      type: "Skills",
      val: [
        "• Novice: Normal household technology is a snap for you.",
        "•• Practiced: Basic household, IT, and automotive maintenance and repairs are easy enough to manage, and you know how to tinker around with simple electronic tech.",
        "••• Skillful: You’ve got enough mechanics savvy to create your own minor-league tech, repair most everyday items, and work simple technomagick with the goods at your command.",
        "•••• Expert: You’re a whiz with typical technology, invent some pretty advanced stuff, and whip up impressive gadgets outside the range of everyday Sleepertech.",
        "••••• Master: A technological artisan, you can design, construct, operate, and repair unique devices and astonishing inventions. If you employ technomagick, then your creations surpass Sleepertech by a pretty wide margin.",
      ],
    },
  ],
  [
    {
      label: "Academics",
      type: "Knowledges",
      val: [
        "• Dabbler: Basic primary and secondary education.",
        "•• Student: Basic university education, equivalentto a two - year degree.",
        "••• Scholar: Advanced university education, equivalent to a four-year degree.",
        "•••• Professor: Advanced specialized study, plus an advanced university-level education.",
        "••••• Master: Refined and advanced scholarship, with highly respected academic achievements.",
      ],
    },
    {
      label: "Computer",
      type: "Knowledges",
      val: [
        "• Dabbler: You know basic computer skills for your time and place.",
        "•• Student: You’ve studied IT systems and can do basic programming.",
        "••• Scholar: Study and experience make you pretty decent with essential systems.",
        "•••• Professor: You’re a respected pro in the computer tech field.",
        "••••• Master: When you’re not making existing systems play fetch for you, you’re crafting new stuff, reworking hardware, and being an overall master of your trade.",
      ],
    },
    {
      label: "Cosmology",
      type: "Knowledges",
      val: [
        "• Dabbler: Student of the mysteries.",
        "•• Student: Occasional voyager.",
        "••• Scholar: Experienced traveler.",
        "•••• Professor: Seasoned explorer.",
        "••••• Master: World-walker.",
      ],
    },
    {
      label: "Enigmas",
      type: "Knowledges",
      val: [
        "• Dabbler: Puzzles intrigue you.",
        "•• Student: Zen koans do not piss you off.",
        "••• Scholar: “You were not put here to ‘Get it,’ Mr. Burton.”",
        "•••• Professor: You clap with one hand inside Schrödinger’s box.",
        "••••• Master: You are an enigma.",
      ],
    },
    {
      label: "Esoterica",
      type: "Knowledges",
      val: [
        "• Dabbler: You’ve skimmed some New Age books or taken a handful of classes in the subject.",
        "•• Student: You’ve devoted some time and energy to esoteric subjects.",
        "••• Scholar: A devoted esotericist, you’ve spent years building up a working knowledge of odd subjects.",
        "•••• Professor: Nowyouunderstandtheinterconnected patterns of arcane disciplines; knowing one allows you to master others more easily.",
        "••••• Master: You possess a profound understanding of esoteric subjects and the practical uses behind them.",
      ],
    },
    {
      label: "Investigation",
      type: "Knowledges",
      val: [
        "• Dabbler: You spend lots of time in the Mystery section of your favorite bookstore.",
        "•• Student: You’ve learned basic criminology.",
        "••• Scholar: Detective work is your trade and passion.",
        "•••• Professor: Clarice Starling comes to you for advice.",
        "••••• Master: Batman.",
      ],
    },
    {
      label: "Law",
      type: "Knowledges",
      val: [
        "• Dabbler: Beat cop.",
        "•• Student: Police sergeant.",
        "••• Scholar: Chief or DA.",
        "•••• Professor: Federal bureau official.",
        "••••• Master: Attorney General.",
      ],
    },
    {
      label: "Medicine",
      type: "Knowledges",
      val: [
        "• Dabbler: You’ve learned basic First Aid and CPR.",
        "•• Student: You can treat minor traumas and illnesses.",
        "••• Scholar: Medical training allows you to pursue more serious treatments.",
        "•••• Professor: You’ve got a professional degree of skill in advanced medicine and surgical procedures.",
        "••••• Master: A noted and respected healer, you’re in demand for your extensive expertise.",
      ],
    },
    {
      label: "Occult",
      type: "Knowledges",
      val: [
        "• Dabbler: You think you know who Crowley was, and you have some New Age books on your shelves.",
        "•• Student: Some of the stuff you’ve heard or read is actually true.",
        "••• Scholar: You’ve got first-hand experience in the world of shadows.",
        "•••• Professor: Study and experience have taught you a respectable amount of genuine lore.",
        "••••• Master: Knowledgeable parties respect your accomplishments and consider you an authority in your own right.",
      ],
    },
    {
      label: "Politics",
      type: "Knowledges",
      val: [
        "• Dabbler: Amateur power-broker.",
        "•• Student: Devotee of influence.",
        "••• Scholar: A skillful manipulator of civil institutions.",
        "•••• Professor: Magnificent bastard.",
        "••••• Master: Machiavelli’s ghost whispers in your ear.",
      ],
    },
    {
      label: "Science",
      type: "Knowledges",
      val: [
        "• Dabbler: You’ve got a typical high school science education and understand the basic principles of your field.",
        "•• Student: You possess an advanced science education and understand the major theories, principles, and concepts of your preferred field.",
        "••• Scholar: You’ve dedicated yourself to scientific inquiry and possess a detailed knowledge of your chosen discipline.",
        "•••• Professor: Impressive scholarship, plus devoted study and research, make you an expert in your field and a master of generalized science.",
        "••••• Master: Very few peers can match your expertise, understanding, and respect within the field.",
      ],
    },
  ],
];
