
export const skills = [
  [
    {
      label: "Alertness",
      type: "Talents",
      val: [
        "• Novice: “I’ve got a bad feeling about this…”",
        "•• Practiced: Your hackles rise at the first sign of trouble.",
        "••• Skillful: You catch the threat beneath a whispered voice.",
        "•••• Expert: You’ve already noted three attackersand mapped four avenues of escape.",
        "••••• Master: Those ninjas might as well be wearing pink neon clown suits.",
      ],
      description: "You sense things coming long before anyone else does. A combination of keen instincts and sharp thinking, this Ability helps you size up situations and respond accordingly. Beast-folk, survivors, bright courtiers and battle-honed veterans have high Alertness ratings.",
      possessed: "Spies, Bodyguards, Feral Kids, Street Survivors, Shapeshifters, War Veterans",
      specialty: "Ambushes, Instincts, Omens, Urban Wastelands, Combat Zones, Covert Pursuit, Warning Signs",
    },
    {
      label: "Art",
      type: "Talents",
      val: [
        "• Novice: You’re creative but unskilled.",
        "•• Practiced: You’ve put some time and work into your chosen medium.",
        "••• Skillful: Professional art could be a viable career option.",
        "•••• Expert: You’re a working pro whose work displays fascinating appeal and skill.",
        "••••• Master: You’re an acknowledged master of your field.",
      ],
      description: "Also known as Artistic Expression, this Talent reflects your ability with a visual or performing art: drawing, singing, acting, writing, painting, dance, sculpture, and so forth. Given such talents, you can work within your chosen medium to produce works of startling power. Depending on your idiom, you might create realistic renderings, engaging exaggerations, or wildly avant-garde experimental art. Higher levels reflect your ability to impress your audience; in art, that means striking a chord of Truth in people even when your work isn’t remotely realistic. As with other related general Abilities, each specialty reflects a different medium or field, of artistic endeavor. Each type of art – dance, painting, etc. – must be purchased as a separate specialty. However, because the principles of art are related even when the techniques differ, you can purchase additional specialties for only four points, assuming you have at least four dots in Art and one specialty already in place. See The Well- Skilled Craftsman (p. 279) for further details.",
      possessed: "Art Students, Fine Artists, Professional Artists, Talented Kids, Dedicated Hobbyists, Reclusive Geniuses, Meditative Ascetics, Mages Who Focus Magick Through Art",
      specialty: "Painting, Video, Singing, Acting, Dance, Mixed Media, CGI, Model-Making, Classical Art, Avant-Garde, Unrefined Intuition, Mad Brilliance, Uncanny Truths, Primitive Techniques, specific musical instruments (Guitar, Drums, Piano, etc.)",
    },
    {
      label: "Athletics",
      type: "Talents",
      val: [
        "• Novice: You were pretty decent in PE class.",
        "•• Practiced: Regular exercise is essential to your life.",
        "••• Skillful: You are one fit sonofabitch!",
        "•••• Expert: Gym-rats and pro athletes take notes from you.",
        "••••• Master: You could qualify for the Olympics… and you might actually compete!",
      ],
      description: "Fitness is your passion. While other folks sit on the sidelines, you’re running races, scoring touchdowns, biking to and from work, and developing prowess with intense practice. Folks don’t usually picture wizards hanging around the gym, but you’re an exception to that stereotype. “A sound mind in a sound body” is your motto. What good is it to be a master of reality, after all, if your reality involves a fat ass and flabby gut? Like Art, Athletics has many different specialties – running, climbing, swimming, and so forth. And like Art, Crafts, and other broad categories, you can buy specialties to reflect different athletic pursuits. (The Well-Skilled Craftsman option applies here as well.)",
      specialty: "Bodybuilding, Cycling, Climbing, Equestrian, Swimming, Survival Training, Extreme Endurance, Flow- Arts, Parkour, Skiing, specific sports (Football, Basketball, Hockey, etc.)",
      possessed: "Jocks, Cyborgs, Fitness Gurus, Personal Trainers, Professional Dancers, Martial Artists, Underwear Models, TV Stars",
    },
    {
      label: "Awareness",
      type: "Talents",
      val: [
        "• Novice: You possess a gift for spotting hiddentruths.",
        "•• Practiced: Magic exists, and you often senseits presence.",
        "••• Skillful: You can see auras, and you understand what those colors mean.",
        "•••• Expert: The supernatural world reveals itself to you in disturbing detail.",
        "••••• Master: You’re so attuned to the mystic realm that many folks consider you insane.",
      ],
      description: "You’ve got uncanny perceptions. While alert folks spot everyday clues, your instincts cue in on the so-called supernatural side of life. Perhaps you’ve simply got that feeling about things – some people do, even if they’re not Awakened as such. More likely, you’ve spent enough time around the magical world to sense its effects in your presence. At lower levels, this Talent grants a nebulous perception of uncanny phenomena; higher ratings in the Trait reveal auras, expose the secretive Night-Folk, and open your eyes to the spiritual Periphery. In game terms, you can use Perception + Awareness to spot paranormal effects, detect magick, recognize Resonance Echoes, and so forth, assuming they’re within close proximity of you. The more successes you roll, the more detailed your impressions become. For a reference chart of aura colors and textures, see Chapter Ten, (p.507).",
      possessed: "Canny Grannies, Wise Spies, Crazy Shamans, Demented Seers, Insightful Kids, Mad Scientists, Those Touched By God",
      specialty: "Omens, Auras, Resonance, Weird Feelings, Mystic Instincts, Hidden Magic, Spiritual Vidare",
    },
    {
      label: "Brawl",
      type: "Talents",
      val: [
        "• Novice: You had a tough childhood.",
        "•• Practiced: You’re from The Bad Part of Town.",
        "••• Skillful: When punches fly, you’re among the last folks standing.",
        "•••• Expert: Extreme fighting champs shiver when you enter the ring.",
        "••••• Master: “See me hit you, you go down.”",
      ],
      description: "You kick ass. Maybe you grew up hard and mean, or maybe you’re schooled in basic self-defense. Either way, your fists and feet are weapons – probably not deadly, but a lot more effective than random swings from unskilled brutes. Not only do you know how to fight, but you’re naturally good at it. You’ve got the skill, will, and training to hurt someone using nothing more than human cunning and animal ferocity. (For armed fighting, see the Melee Skill, and for refined unarmed techniques, see the Martial Arts Skill. Both appear below.)",
      possessed: "Bikers, Brawlers, Bullies, Former Punching Bags, Bodyguards, Military Veterans, Scary Folks With Bad Tempers",
      specialty: "Barroom, Boxing, Beast-Form Fighting, Dirty Fighting, Disarming, Peaceful Warrior",
    },
    {
      label: "Empathy",
      type: "Talents",
      val: [
        "• Novice: You’re pretty decent at noticing emotional cues.",
        "•• Practiced: You’re the crying shoulder for your friends.",
        "••• Skillful: It’s fairly hard to deceive you.",
        "•••• Expert: Even below the surface, a person’s true feelings seem obvious to you.",
        "••••• Master: To your eyes, most people are open books.",
      ],
      description: "An innate sense of emotional energies, this Talent provides you with insight – perhaps more insight than you might want – into how the people around you feel. Ideally, this helps you understand them better and perhaps allows you to calm, rouse, or otherwise adjust their emotional state. On the flipside, it might leave you vulnerable to their passions (a common fault among Ecstatic mages), or it could leave them vulnerable to your machinations. Combined with Mindbased Effects, Empathy can be a potent tool – or weapon – in the hands of an Awakened character. For details, see Mundane Skills and Magickal Effects in Chapter Ten, (pp. 532-535).",
      possessed: "Ecstatic Mages, Shamans, Healers, Seducers, Sales Reps, Therapists, Trusted Friends, Nephandi",
      specialty: "Hidden Feelings, Subtle Cues, Emotional Manipulation, Trust, Sensing Emotions, Life-Force Fluctuations, Interpersonal Psychology, Seeing Past the Mask, “I Know What You Need”",
    },
    {
      label: "Expression",
      type: "Talents",
      val: [
        "• Novice: When you speak, folks notice.",
        "•• Practiced: Your passions capture other people’s interest.",
        "••• Skillful: You rock the crowd with a voice that’s loud.",
        "•••• Expert: In this media-glutted world, you still blaze bright.",
        "••••• Master: Poets, prophets, and politicians wish they were you. Possessed By: Rock Stars,",
      ],
      description: "Life is your canvas, and you excel at making impressions upon it. Through theatrical flair and audience psychology, you can rouse emotions, shift opinions, and grab the spotlight in social situations. Although this Trait can be used to handle any social situation, it’s best used to make general impressions. For specific artistic endeavors, see Art, above.",
      possessed: "Rock Stars, Media Pundits, Ecstatic Mages, Executives, Poets, Leaders, Politicians, Bloggers, Rabble- Rousers, Hip-Hop MCs, Professional Celebrities",
      specialty: "Passion Plays, Poetic Eloquence, Motivational Speaking, Tactical Rhetoric, Preaching, Command, Shut-Downs, Rocking the Mic",
    },
    {
      label: "Intimidation",
      type: "Talents",
      val: [
        "• Novice: Playground terror.",
        "•• Practiced: Clique leader.",
        "••• Skillful: Professional dominant.",
        "•••• Expert: Alpha wolf.",
        "••••• Master: Queen or king of all you survey.",
      ],
      description: "You scare people – perhaps not through overt threats (although, of course, that works too), but by the simple virtue of your presence. When you choose to, you can dominate most situations. Maybe you understand the unconscious cues of social alpha-ism or have a way with cutting words. Or perhaps you’re simply big enough, mean enough or don’t-give-a-fuck enough to inspire submission. Whatever your secret might be, this Talent gives you an edge when staring down other people, beasts, and possibly other entities as well.",
      possessed: "Men in Black, Cyborgs, Cops, Witches, Mad Scientists, Outlaws, Bullies, Beast-Folk, Pro Doms, Drill Sergeants, Samuel L. Jackson",
      specialty: "Bad Cop, BDSM, Pack Hierarchy, Cold Stare, Brutal Threats, Topping From Below, Pants- Crapping Terror"
    },
    {
      label: "Leadership",
      type: "Talents",
      val: [
        "• Novice: Head cheerleader.",
        "•• Practiced: Quarterback.",
        "••• Skillful: Executive.",
        "•••• Expert: Tycoon.",
        "••••• Master: Nick Fury.",
      ],
      description: "A more refined sort of control, this Talent helps you inspire other folks to follow your lead. It might involve commanding presence, assertive words, clear determination, or simply the Right Stuff when said stuff is needed. When you bark, folks hop – not always with compliance, but with, at the very least, a grudging admission that you seem to know what you’re doing… even when you don’t.",
      possessed: "Officers, Managers, Pundits, Preachers, Teachers, Team Leaders, Cult Leaders, Gang Leaders, Politicians",
      specialty: "Competent, Inspiring, Regal, Harsh, Do-Or-Die, Soft-Voiced Command",
    },
    {
      label: "Streetwise",
      type: "Talents",
      val: [
        "• Novice: Rock musician.",
        "•• Practiced: Suburban dope dealer.",
        "••• Skillful: Hip-Hop MC.",
        "•••• Expert: Gang leader.",
        "••••• Master: Gang lord. Possessed By: Bartenders, Hookers,",
      ],
      description: "The underworld is your home, and you know it pretty well. Folks who normally don’t talk to no one will open up to you. Probably raised in or around the streets, you understand the codes and cues outside the law. In addition to some minor tricks of the trade (jimmying locks, fencing goods, swiping stuff when no one’s looking), you know how to move and speak and otherwise fit in where cops and angels fear to tread.",
      possessed: "Bartenders, Hookers, Hackers, Pimps, Street People, Cops, Detectives, Street Ministers, Musicians, Runaways, Drug Dealers, Activists, Journalists, Taxi Drivers",
      specialty: "Theft, Survival Skills, Outlaw Hacker Culture, Crash Space, Street Politics, Urban Tribes, Trust, Hiding Spots, Sex Trade, Drug Trade, Music Culture, Gangs, Seeing Nothing Yet Everything",
    },
    {
      label: "Subterfuge",
      type: "Talents",
      val: [
        "• Novice: Cute kid.",
        "•• Practiced: Small-time hustler.",
        "••• Skillful: Successful lawyer.",
        "•••• Expert: Career politician.",
        "••••• Master: Master spy.",
      ],
      description: "You’re good at winning people’s trust and then turning it to your advantage – and also good at spotting folks who try to do the same thing to you. (This second element, incidentally, replaces the old Ability Sense Deception.) Perhaps you use your powers for good… but probably not. A trade secret for sneaks, gossips, grifters, and frauds, this Talent helps you get around social barriers, figure out what people want, and then appeal to their desires. It doesn’t have to involve outright lying, but let’s just say you’re really good at lawyering the truth.",
      possessed: "Syndicate Agents, Secret Agents, Home- Wreckers, Ad Agency Personnel, Lobbyists, Crooks, Shapeshifters, Infiltrators, Embezzlers, Hustlers, Attorneys, Sociopaths",
      specialty: "Con Games, Sexual Manipulation, False Innocence, Politics, Law, Cheating, Undermining Opposition, Sensing Deceptions",
    }
  ],
  [
    {
      label: "Crafts",
      type: "Skills",
      val: [
        "• Novice: You sorta know what you’re doing.",
        "•• Practiced: Basic skills have given way to working knowledge.",
        "••• Skillful: You’re pretty damn good, if you must say so yourself!",
        "•••• Expert: You’re highly respected within your field.",
        "••••• Master: There’s little you can’t do when you set your mind to doing it.",
      ],
    },
    {
      label: "Drive",
      type: "Skills",
      val: [
        "• Novice: Sunday driver.",
        "•• Practiced: Typical American.",
        "••• Skillful: New York taxi driver.",
        "•••• Expert: Professional racer.",
        "••••• Master: Bond – James Bond.",
      ],
    },
    {
      label: "Etiquette",
      type: "Skills",
      val: [
        "• Novice: You can attend fine restaurants without embarrassing yourself.",
        "•• Practiced: You’ve got impressive manners and a sense for saying the right things.",
        "••• Skillful: Wonderfully cultured, you know your way around a meal, party, or conversation.",
        "•••• Expert: A social chameleon, you put folks at ease almost anywhere.",
        "••••• Master: You’re a valued guest in nearly any situation.",
      ],
    },
    {
      label: "Firearms",
      type: "Skills",
      val: [
        "• Novice: Gun range newbie.",
        "•• Practiced: Hunter.",
        "••• Skillful: Typical cop or soldier.",
        "•••• Expert: Sharpshooter.",
        "••••• Master: Frank Castle.",
      ],
    },
    {
      label: "Martial Arts",
      type: "Skills",
      val: [
        "• Novice: Raw beginner.",
        "•• Practiced: Experienced student.",
        "••• Skillful: Devotee.",
        "•••• Expert: Accomplished combatant.",
        "••••• Master: Formidable master.",
      ],
    },
    {
      label: "Meditation",
      type: "Skills",
      val: [
        "• Novice: You can ground and center for short periods of time.",
        "•• Practiced: Regular practice has deepened and extended your abilities.",
        "••• Skillful: Even under distracting conditions, you know how to find your center.",
        "•••• Expert: “Use the Force, Luke…”",
        "••••• Master: An island of calm is yours whenever you want or need it.",
      ],
    },
    {
      label: "Melee",
      type: "Skills",
      val: [
        "• Novice: You can swing a club or blade around without hurting yourself… much.",
        "•• Practiced: You’ve earned a bit of skill… maybe even enough for a real-life fight.",
        "••• Skillful: You’re kinda badass.",
        "•••• Expert: You’re seriously badass.",
        "••••• Master: Your skill intimidates the pros.",
      ],
    },
    {
      label: "Research",
      type: "Skills",
      val: [
        "• Novice: Buffy.",
        "•• Practiced: Anya.",
        "••• Skillful: Willow.",
        "•••• Expert: Giles.",
        "••••• Master: Fred.",
      ],
    },
    {
      label: "Stealth",
      type: "Skills",
      val: [
        "• Novice: With dark clothes, you might not be spotted at night.",
        "•• Practiced: You often sneak out past your parents.",
        "••• Skillful: A genuine sneak, you elude casual detection.",
        "•••• Expert: Just doin’ what a ninja’s gotta do…",
        "••••• Master: Batman’s taking notes.",
      ],
    },
    {
      label: "Survival",
      type: "Skills",
      val: [
        "• Novice: You’ve done some day-hikes on established trails.",
        "•• Practiced: Plenty of time outdoors has taught you decent skills.",
        "••• Skillful: You can live off the land, make traps, and spot most obvious hazards.",
        "•••• Expert: You’d probably survive the Hunger Games.",
        "••••• Master: The wilderness is your full-time home.",
      ],
    },
    {
      label: "Technology",
      type: "Skills",
      val: [
        "• Novice: Normal household technology is a snap for you.",
        "•• Practiced: Basic household, IT, and automotive maintenance and repairs are easy enough to manage, and you know how to tinker around with simple electronic tech.",
        "••• Skillful: You’ve got enough mechanics savvy to create your own minor-league tech, repair most everyday items, and work simple technomagick with the goods at your command.",
        "•••• Expert: You’re a whiz with typical technology, invent some pretty advanced stuff, and whip up impressive gadgets outside the range of everyday Sleepertech.",
        "••••• Master: A technological artisan, you can design, construct, operate, and repair unique devices and astonishing inventions. If you employ technomagick, then your creations surpass Sleepertech by a pretty wide margin.",
      ],
    },
  ],
  [
    {
      label: "Academics",
      type: "Knowledges",
      val: [
        "• Dabbler: Basic primary and secondary education.",
        "•• Student: Basic university education, equivalentto a two - year degree.",
        "••• Scholar: Advanced university education, equivalent to a four-year degree.",
        "•••• Professor: Advanced specialized study, plus an advanced university-level education.",
        "••••• Master: Refined and advanced scholarship, with highly respected academic achievements.",
      ],
    },
    {
      label: "Computer",
      type: "Knowledges",
      val: [
        "• Dabbler: You know basic computer skills for your time and place.",
        "•• Student: You’ve studied IT systems and can do basic programming.",
        "••• Scholar: Study and experience make you pretty decent with essential systems.",
        "•••• Professor: You’re a respected pro in the computer tech field.",
        "••••• Master: When you’re not making existing systems play fetch for you, you’re crafting new stuff, reworking hardware, and being an overall master of your trade.",
      ],
    },
    {
      label: "Cosmology",
      type: "Knowledges",
      val: [
        "• Dabbler: Student of the mysteries.",
        "•• Student: Occasional voyager.",
        "••• Scholar: Experienced traveler.",
        "•••• Professor: Seasoned explorer.",
        "••••• Master: World-walker.",
      ],
    },
    {
      label: "Enigmas",
      type: "Knowledges",
      val: [
        "• Dabbler: Puzzles intrigue you.",
        "•• Student: Zen koans do not piss you off.",
        "••• Scholar: “You were not put here to ‘Get it,’ Mr. Burton.”",
        "•••• Professor: You clap with one hand inside Schrödinger’s box.",
        "••••• Master: You are an enigma.",
      ],
    },
    {
      label: "Esoterica",
      type: "Knowledges",
      val: [
        "• Dabbler: You’ve skimmed some New Age books or taken a handful of classes in the subject.",
        "•• Student: You’ve devoted some time and energy to esoteric subjects.",
        "••• Scholar: A devoted esotericist, you’ve spent years building up a working knowledge of odd subjects.",
        "•••• Professor: Nowyouunderstandtheinterconnected patterns of arcane disciplines; knowing one allows you to master others more easily.",
        "••••• Master: You possess a profound understanding of esoteric subjects and the practical uses behind them.",
      ],
    },
    {
      label: "Investigation",
      type: "Knowledges",
      val: [
        "• Dabbler: You spend lots of time in the Mystery section of your favorite bookstore.",
        "•• Student: You’ve learned basic criminology.",
        "••• Scholar: Detective work is your trade and passion.",
        "•••• Professor: Clarice Starling comes to you for advice.",
        "••••• Master: Batman.",
      ],
    },
    {
      label: "Law",
      type: "Knowledges",
      val: [
        "• Dabbler: Beat cop.",
        "•• Student: Police sergeant.",
        "••• Scholar: Chief or DA.",
        "•••• Professor: Federal bureau official.",
        "••••• Master: Attorney General.",
      ],
    },
    {
      label: "Medicine",
      type: "Knowledges",
      val: [
        "• Dabbler: You’ve learned basic First Aid and CPR.",
        "•• Student: You can treat minor traumas and illnesses.",
        "••• Scholar: Medical training allows you to pursue more serious treatments.",
        "•••• Professor: You’ve got a professional degree of skill in advanced medicine and surgical procedures.",
        "••••• Master: A noted and respected healer, you’re in demand for your extensive expertise.",
      ],
    },
    {
      label: "Occult",
      type: "Knowledges",
      val: [
        "• Dabbler: You think you know who Crowley was, and you have some New Age books on your shelves.",
        "•• Student: Some of the stuff you’ve heard or read is actually true.",
        "••• Scholar: You’ve got first-hand experience in the world of shadows.",
        "•••• Professor: Study and experience have taught you a respectable amount of genuine lore.",
        "••••• Master: Knowledgeable parties respect your accomplishments and consider you an authority in your own right.",
      ],
    },
    {
      label: "Politics",
      type: "Knowledges",
      val: [
        "• Dabbler: Amateur power-broker.",
        "•• Student: Devotee of influence.",
        "••• Scholar: A skillful manipulator of civil institutions.",
        "•••• Professor: Magnificent bastard.",
        "••••• Master: Machiavelli’s ghost whispers in your ear.",
      ],
    },
    {
      label: "Science",
      type: "Knowledges",
      val: [
        "• Dabbler: You’ve got a typical high school science education and understand the basic principles of your field.",
        "•• Student: You possess an advanced science education and understand the major theories, principles, and concepts of your preferred field.",
        "••• Scholar: You’ve dedicated yourself to scientific inquiry and possess a detailed knowledge of your chosen discipline.",
        "•••• Professor: Impressive scholarship, plus devoted study and research, make you an expert in your field and a master of generalized science.",
        "••••• Master: Very few peers can match your expertise, understanding, and respect within the field.",
      ],
    },
  ],
];
